version: '3'

services:
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443 
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=mcca_docker
      - MYSQL_USER=mcca_user
      - MYSQL_PASSWORD=pass
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306